### ISSUE TITLE
Any update on repo WordRecognition-CoreML-MLKit

### ISSUE THREAD

**Issue by jrkingray** [motlabs/awesome-ml-demos-with-ios#22]
Hi Contributors,

I found this repo from my colleague and I am very interested in this WordRecognition-CoreML-MLKit. Has there been any update on this repo?

Thanks
Rui

**Comment by tucan9389** [comment]
@jrkingray 
Hi, thanks for your issue.
The repo hasn't prepared yet but you can make your own the following steps.
1. Text Detection
2. Words Extraction
3. Get the nearest word from the middle position on the screen.
4. Cropping the word
5. Text Recognition (using the cropping word image)

**Comment by jrkingray** [comment]
Thanks@tucan9389
