### ISSUE TITLE
Deeplab segmentation ios

### ISSUE THREAD

**Issue by essalahsouad** [motlabs/awesome-ml-demos-with-ios#27]
i used deeplab model on real-time ios application but i got very slow capture .did there any solution to improve fps??

**Comment by tucan9389** [comment]
What kind of model's file type? `tflite` or `mlmodel`?
If you used `tflite`, you can improve performance with selecting GPU by using TensorFlowLite library (MLKit does not support GPU on iOS yet) with Objective-C++ code.
Or if you used `mlmodel`, improve with [quantization](https://developer.apple.com/documentation/coreml/reducing_the_size_of_your_core_ml_app). But this method might drop the model's accuracy.

**Comment by essalahsouad** [comment]
@thnx for your full reply, i used mlmodel , knowing that my model's size is 8mo should I reduce more the size ?

**Comment by tucan9389** [comment]
@essalahsouad 
Sorry for the late reply. In my [ObjectSegmentation-CoreML](https://github.com/tucan9389/ObjectSegmentation-CoreML) repo, the quantization model test does not lower the inference time. 

Theoretically, the quantized model could reduce the amount of calculation and lower the inference time. But the Core ML's quantized model doesn't. And I don't know why.

You can check the model quantization in detail on [this post](https://heartbeat.fritz.ai/8-bit-quantization-and-tensorflow-lite-speeding-up-mobile-inference-with-low-precision-a882dfcafbbd) and [this paper](https://arxiv.org/pdf/1712.05877.pdf).

Here is [my performance test](https://github.com/tucan9389/ObjectSegmentation-CoreML/issues/2) on iPhone XS vs iPhone X for each quantized deeplab v3 model.

**Comment by essalahsouad** [comment]
@tucan9389 
Thank you for your detailed response. I appreciate it.
